name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dummybranch/
      - name: use NodeJs
        uses: seupfornode
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
          

